Bolsa_Empleados/Controllers/AdministradorMVCController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Bolsa_Empleados.Controllers
{
   
    public class AdministradorMVCController : Controller
    {
        Bolsa_de_EmpleadosEntities1 db = new Bolsa_de_EmpleadosEntities1();

        public ActionResult Index(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        [HttpPost]
        public ActionResult Index(string Correo_Administrador, string Contraseña_Administrador)
        {

            if (!string.IsNullOrEmpty(Correo_Administrador) && !string.IsNullOrEmpty(Contraseña_Administrador))
            {
                var user =  db.ADMINISTRADORs.FirstOrDefault(a => a.Correo_Administrador == Correo_Administrador && a.Contraseña_Administrador == Contraseña_Administrador);
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(user.Correo_Administrador, true);
                    return RedirectToAction("Index", "PosterMVC");
                }
                else
                {
                    return RedirectToAction("Index", new { message = "No encontramos tus datos" });
                }
            }
            else
            {
                return RedirectToAction("Index", new { message = "Llena los campos vacios para poder iniciar sesion" });
            }
        }

        public ActionResult IndexNumero_paginacion()
        {
            IEnumerable<NUMERO_DE_PAGINACION> numero = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Administrador");
            var consumirApi = hc.GetAsync("Administrador");
            consumirApi.Wait();
            var readdata = consumirApi.Result;

            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<NUMERO_DE_PAGINACION>>();
                displaydata.Wait();

                numero = displaydata.Result;
            }

            return View(numero);
        }

        public ActionResult Edit(int? id)
        {         
            NUMERO_DE_PAGINACION NUMERO = db.NUMERO_DE_PAGINACION.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (NUMERO == null)
            {
                return HttpNotFound();
            }
            return View(NUMERO);
        }

        // POST: Poster/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Numero_de_Paginas")] NUMERO_DE_PAGINACION NUMERO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(NUMERO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexNumero_paginacion");
            }
            return View(NUMERO);
        }


        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "PosterMVC");
        }
    }
}

Bolsa_Empleados/Views/AdministradorMVC/Edit.cshtml
@model Bolsa_Empleados.NUMERO_DE_PAGINACION

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NUMERO DE VACANTES</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.Label("Numero de Vacantes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero_de_Paginas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero_de_Paginas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("Index", "AdministradorMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/AdministradorMVC/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Report Login Form Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Report Login Form Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- //Meta tag Keywords -->
    <link href="//fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap" rel="stylesheet">
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/DiseñoLogin/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->

    <link rel="stylesheet" href="~/DiseñoLogin/css/font-awesome.min.css" type="text/css" media="all">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

</head>
<body>

    <!-- form section start -->
    <section class="w3l-hotair-form">
        <h1>Vacantes.net</h1>
        <div class="container">

            @{
                if (!string.IsNullOrEmpty(ViewBag.Message))
                { <br />
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.Message
                    </div>
                }


            }
            <!-- /form -->
            <div class="workinghny-form-grid">
                <div class="main-hotair">
                    <div class="content-wthree">
                        <h2>Log In</h2>
                        <form action="~/AdministradorMVC/Index" method="post" class="login">
                            <input type="email" class="text" name="Correo_Administrador" placeholder="Email" required="" autofocus>
                            <input type="password" class="password" name="Contraseña_Administrador" placeholder="User Password" required="" autofocus>
                            <button class="btn" type="submit">Log In</button>
                        </form>

                    </div>
                    <div class="w3l_form align-self">
                        <div class="left_grid_info">
                            <img src="~/DiseñoLogin/images/1.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
            <!-- //form -->
        </div>
        <!-- copyright-->
        <div class="copyright text-center">
            <p class="copy-footer-29">
                © 2021 Report Login Form. All rights reserved | Design by <a href="https://w3layouts.com">W3layouts</a>
            </p>
        </div>
        <!-- //copyright-->
    </section>
    <!-- //form section start -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

Bolsa_Empleados/Views/AdministradorMVC/IndexNumero_paginacion.cshtml
@model IEnumerable<Bolsa_Empleados.NUMERO_DE_PAGINACION>

@{
    ViewBag.Title = "IndexNumero_paginacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Numero_de_Paginas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Numero_de_Paginas)
        </td>
        <td>
            <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Edit", "AdministradorMVC", new { id = item.id})"> <i class="glyphicon glyphicon-edit"></i> Editar</a>
        </td>
    </tr>
}

</table>