Bolsa_Empleados/Controllers/PosterMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bolsa_Empleados.Models;
using System.Net.Http;
using System.Net;
using System.Data.Entity;

namespace Bolsa_Empleados.Controllers
{
    public class PosterMVCController : Controller
    {
        Bolsa_de_EmpleadosEntities1 db = new Bolsa_de_EmpleadosEntities1();

        // GET: PosterMVC
        public ActionResult Index()
        {
            IEnumerable<DATOS_VACANTE> poster = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Poster");
            var consumirApi = hc.GetAsync("Poster");
            consumirApi.Wait();
            var readdata = consumirApi.Result;

            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<DATOS_VACANTE>>();
                displaydata.Wait();

                poster = displaydata.Result;
            }

            return View(poster);
        }


        public ActionResult Index2([Bind(Include = "id,CATEGORIA1")] CATEGORIA CATEGORIA)
        {
           
            var categoria = db.CATEGORIAS.Where(x => x.id == CATEGORIA.id).ToList();

            var datos = new List<DATOS_VACANTE>();
            foreach (var item in categoria)
            {
                datos = db.DATOS_VACANTE.Where(x => x.Categoria == item.CATEGORIA1).ToList();
            }

            foreach (var item in categoria)
            {
                ViewBag.categoria = item.CATEGORIA1;
            }

            datos.Reverse();
            return View(datos);
        }

        public ActionResult IndexCrud()
        {
            IEnumerable<DATOS_VACANTE> poster = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Poster");
            var consumirApi = hc.GetAsync("Poster");
            consumirApi.Wait();
            var readdata = consumirApi.Result;

            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<DATOS_VACANTE>>();
                displaydata.Wait();

                poster = displaydata.Result;
            }

            return View(poster);
        }


        public ActionResult Create()
        {
            ViewBag.items = db.CATEGORIAS.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DATOS_VACANTE Poster)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Poster");
            var InsertarPosster = hc.PostAsJsonAsync<DATOS_VACANTE>("Poster",Poster);
            InsertarPosster.Wait();

            var savedata = InsertarPosster.Result;
            if (savedata.IsSuccessStatusCode)
            {
                return RedirectToAction("IndexCrud");
            }
            return View("Create");
        }


        public ActionResult Edit(int? id)
        {
            ViewBag.items = db.CATEGORIAS.ToList();
            DATOS_VACANTE VACANTE = db.DATOS_VACANTE.Find(id);         

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (VACANTE == null)
            {
                return HttpNotFound();
            }
            return View(VACANTE);
        }

        // POST: Poster/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Compañia,Tipo,Posicion,Ubicacion,Categoria,Descripcion_Trabajo,Como_Aplicar,Email")] DATOS_VACANTE VACANTE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(VACANTE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexCrud");
            }
            return View(VACANTE);
        }


        public ActionResult Editar(int? id)
        {
            ViewBag.items = db.CATEGORIAS.ToList();
            DATOS_VACANTE VACANTE = db.DATOS_VACANTE.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (VACANTE == null)
            {
                return HttpNotFound();
            }
            return View(VACANTE);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "id,Compañia,Tipo,Posicion,Ubicacion,Categoria,Descripcion_Trabajo,Como_Aplicar,Email")] DATOS_VACANTE VACANTE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(VACANTE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(VACANTE);
        }

        public ActionResult Delete(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Poster");

            var delrecord = hc.DeleteAsync("Poster/" + id.ToString());
            delrecord.Wait();

            var displaydata = delrecord.Result;
            if (displaydata.IsSuccessStatusCode)
            {
                return RedirectToAction("IndexCrud");
            }

            return View("IndexCrud");
        }

        public ActionResult Borrar(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Poster");

            var delrecord = hc.DeleteAsync("Poster/" + id.ToString());
            delrecord.Wait();

            var displaydata = delrecord.Result;
            if (displaydata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Index");
        }
    }
}

Bolsa_Empleados/Views/PosterMVC/Create.cshtml
@model Bolsa_Empleados.DATOS_VACANTE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Vacante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Compañia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compañia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compañia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categoria", new SelectList(ViewBag.items, "CATEGORIA1", "CATEGORIA1"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_Trabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion_Trabajo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_Trabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Como_Aplicar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Como_Aplicar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Como_Aplicar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Vacante" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("IndexCrud", "PosterMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/PosterMVC/Edit.cshtml
@model Bolsa_Empleados.DATOS_VACANTE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Editar Vacante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Compañia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compañia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compañia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categoria", new SelectList(ViewBag.items, "CATEGORIA1", "CATEGORIA1"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_Trabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion_Trabajo, new { htmlAttributes = new { @class = "form-control", cols = "50", row = "10" } })
                @Html.ValidationMessageFor(model => model.Descripcion_Trabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Como_Aplicar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Como_Aplicar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Como_Aplicar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("IndexCrud", "PosterMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/PosterMVC/Editar.cshtml
@model Bolsa_Empleados.DATOS_VACANTE

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Editar Vacante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Compañia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compañia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compañia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categoria", new SelectList(ViewBag.items, "CATEGORIA1", "CATEGORIA1"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_Trabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion_Trabajo, new { htmlAttributes = new { @class = "form-control", cols = "50", row = "10" } })
                @Html.ValidationMessageFor(model => model.Descripcion_Trabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Como_Aplicar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Como_Aplicar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Como_Aplicar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("Index", "PosterMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/PosterMVC/Index.cshtml
@model IEnumerable<Bolsa_Empleados.DATOS_VACANTE>

@{
    ViewBag.Title = "Index";
}


<h2>@ViewBag.Message</h2>



@section styles{
    <link href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

}



<center><h2>Vacantes</h2></center>
<br />
<br />

@using (Bolsa_de_EmpleadosEntities1 db = new Bolsa_de_EmpleadosEntities1())
{

    var numero = db.NUMERO_DE_PAGINACION.ToList();
    int nun = 0;
    foreach (var item in numero)
    {
        nun = item.Numero_de_Paginas;
    }


    var categorias = (from datos in db.CATEGORIAS select datos).ToList();

    var d = db.CATEGORIAS.ToList();
    var solicitud = db.ADMINISTRADORs.ToList();

    foreach (var item in categorias)
    {

        <table class="table" id="tabledemo">

            @Html.ActionLink(item.CATEGORIA1, "Index2", new { id = item.id })

            <thead>
             
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ubicacion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Posicion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Compañia)
                    </th>
                    <th></th>

                    @foreach (var itera in solicitud)
                    {
                        if (itera.Correo_Administrador == HttpContext.Current.User.Identity.Name)
                        {
                            <th></th>
                        }
                    }

                </tr>

            </thead>

            <tbody>

                

                @foreach (var ite in Model.Where(x => x.Categoria == item.CATEGORIA1).OrderByDescending(x=> x.id).Take(nun))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => ite.Ubicacion)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => ite.Posicion)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => ite.Compañia)
                        </td>

                        <td>
                            <a class="btn btn-primary" data-toggle="modal" data-target="#@ite.id">
                                <i class="bi bi-info-circle"></i> Informacion

                            </a>

                            <!-- Modal -->
                            <div class="modal fade" id="@ite.id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">@ite.Categoria</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            <h1>@ite.Compañia</h1>
                                            @ite.Ubicacion
                                            <br />
                                            @ite.Posicion - @ite.Tipo
                                            <br />
                                            <br />
                                            @ite.Descripcion_Trabajo
                                            <br />
                                            <br />
                                            Como Aplicar?
                                            <br />
                                            <br />
                                            @ite.Como_Aplicar
                                            <br />
                                            <br />
                                            <a href="mailto:@ite.Email?subject=Subject Using Mailto.co.uk&body=Email Using Mailto.co.uk"> @ite.Email</a>



                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>


                        @foreach (var itera in solicitud)
                        {
                            if (itera.Correo_Administrador == HttpContext.Current.User.Identity.Name)
                            {
                    <td>
                        <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Editar", "PosterMVC", new { id = ite.id})"> <i class="glyphicon glyphicon-edit"></i> Editar</a>
                        <a class="btn btn-danger btn-xs" title="Editar" href="@Url.Action("Borrar", "PosterMVC", new { id = ite.id})"> <i class="glyphicon glyphicon-trash"></i> Borrar</a>
                    </td>
                            }
                        }

                    </tr>
                }
            </tbody>
        </table>

        <br />
        <br />
        <br />
    }

}

@section scripts{
    <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <script>
        $('.table').DataTable({
            "paging": false,
            "ordering": false,
            "info": false,

            "language": {
                "lengthMenu": "Mostrando _MENU_ registros por pagina",
                "zeroRecords": "No encontrado  - Lo sentimos",
                "info": "Mostrando pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros disponibles",
                "infoFiltered": "(filtrado de _MAX_  registros en total)",
                "search": "Buscar",
                "next": "Siguiente",
                "previous": "Anterior",

            }
        });
    </script>
}

Bolsa_Empleados/Views/PosterMVC/Index2.cshtml
@model IEnumerable<Bolsa_Empleados.DATOS_VACANTE>

@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    <link href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

}

@using (Bolsa_de_EmpleadosEntities1 db = new Bolsa_de_EmpleadosEntities1())
 {
    var categorias = (from datos in db.CATEGORIAS select datos).ToList();

    var d = db.CATEGORIAS.ToList();
    var solicitud = db.ADMINISTRADORs.ToList();



    <h2>@ViewBag.categoria</h2>


    <table class="table " id="tabledemo">
        <thead>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ubicacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Posicion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Compañia)
                </th>
                <th></th>

                @foreach (var itera in solicitud)
                {
                    if (itera.Correo_Administrador == HttpContext.Current.User.Identity.Name)
                    {
                        <th></th>
                    }
                }
            </tr>

        </thead>

        <tbody>

            @foreach (var ite in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => ite.Ubicacion)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => ite.Posicion)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => ite.Compañia)
                    </td>

                    <td>
                        <a class="btn btn-info" data-toggle="modal" data-target="#@ite.id">
                            <i class="bi bi-info-circle"></i> Informacion

                        </a>

                        <!-- Modal -->
                        <div class="modal fade" id="@ite.id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">@ite.Categoria</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">

                                        <h1>@ite.Compañia</h1>
                                        @ite.Ubicacion
                                        <br />
                                        @ite.Posicion - @ite.Tipo
                                        <br />
                                        <br />
                                        @ite.Descripcion_Trabajo
                                        <br />
                                        <br />
                                        Como Aplicar?
                                        <br />
                                        <br />
                                        @ite.Como_Aplicar
                                        <br />
                                        <br />
                                        <a href="mailto:@ite.Email?subject=Subject Using Mailto.co.uk&body=Email Using Mailto.co.uk"> @ite.Email</a>


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>

                    @foreach (var itera in solicitud)
                    {
                        if (itera.Correo_Administrador == HttpContext.Current.User.Identity.Name)
                        {
                <td>
                    <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Editar", "PosterMVC", new { id = ite.id})"> <i class="glyphicon glyphicon-edit"></i> Editar</a>
                    <a class="btn btn-danger btn-xs" title="Editar" href="@Url.Action("Borrar", "PosterMVC", new { id = ite.id})"> <i class="glyphicon glyphicon-trash"></i> Borrar</a>
                </td>
                        }
                    }

                </tr>
            }

        </tbody>

    </table>



}

@section scripts{
    <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tabledemo').DataTable({
            "pageLength": 20,
            lengthMenu: [20],
            "language": {
                "lengthMenu": "Mostrando _MENU_ registros por pagina",
                "zeroRecords": "No encontrado  - Lo sentimos",
                "info": "Mostrando pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros disponibles",
                "infoFiltered": "(filtrado de _MAX_  registros en total)",
                "search": "Buscar",
                "next": "Siguiente",
                "previous": "Anterior",

            },
            "ordering": false,


        });
    </script>
}