Bolsa_Empleados/Controllers/CategoriaMVCController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Bolsa_Empleados.Models;

namespace Bolsa_Empleados.Controllers
{
    public class CategoriaMVCController : Controller
    {
        Bolsa_de_EmpleadosEntities1 db = new Bolsa_de_EmpleadosEntities1();

        // GET: CategoriaMVC
        public ActionResult Index()
        {
            IEnumerable<CATEGORIA> categoria = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Categorias");
            var consumirApi = hc.GetAsync("Categorias");
            consumirApi.Wait();
            var readdata = consumirApi.Result;

            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<CATEGORIA>>();
                displaydata.Wait();

                categoria = displaydata.Result;
            }

            return View(categoria);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CATEGORIA categoria)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Categorias");
            var InsertarPosster = hc.PostAsJsonAsync<CATEGORIA>("Categorias", categoria);
            InsertarPosster.Wait();

            var savedata = InsertarPosster.Result;
            if (savedata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        public ActionResult Edit(int? id)
        {
            CATEGORIA CATEGORIA = db.CATEGORIAS.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (CATEGORIA == null)
            {
                return HttpNotFound();
            }
            return View(CATEGORIA);
        }

        // POST: Categorias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,CATEGORIA1")] CATEGORIA CATEGORIA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(CATEGORIA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(CATEGORIA);
        }



        public ActionResult Delete(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44343/api/Categorias");

            var delrecord = hc.DeleteAsync("Categorias/" + id.ToString());
            delrecord.Wait();

            var displaydata = delrecord.Result;
            if (displaydata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("IndexCrud");
        }

    }
}

Bolsa_Empleados/Views/CategoriaMVC/Create.cshtml
@model Bolsa_Empleados.CATEGORIA

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Categoria</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("CATEGORIA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORIA1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CATEGORIA1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Categoria" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("Index", "CategoriaMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/CategoriaMVC/Delete.cshtml
@model Bolsa_Empleados.CATEGORIA

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Borrar</h2>

<h3>Esta seguro que desea eliminarla?</h3>
<br />
<br />
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("CATEGORIA")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA1)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Bolsa_Empleados/Views/CategoriaMVC/Edit.cshtml
@model Bolsa_Empleados.CATEGORIA

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Categoria</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.Label("CATEGORIA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORIA1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CATEGORIA1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <div>
        <a class="btn btn-primary" href="@Url.Action("Index", "CategoriaMVC")"><i class="glyphicon glyphicon-menu-left"></i> Regresar al Listado</a>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bolsa_Empleados/Views/CategoriaMVC/Index.cshtml
@model IEnumerable<Bolsa_Empleados.CATEGORIA>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categorias</h2>
<br />

<p>
    <a class="btn btn-primary" href="@Url.Action("Create","CategoriaMVC")"><i class="glyphicon glyphicon-plus"></i> Agregar Categoria</a>
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("CATEGORIA")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CATEGORIA1)
            </td>
            <td>
                <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Edit", "CategoriaMVC", new { id = item.id})"> <i class="glyphicon glyphicon-edit"></i>Editar</a>
                <a class="btn btn-danger btn-xs" title="Editar" href="@Url.Action("Delete", "CategoriaMVC", new { id = item.id})"> <i class="glyphicon glyphicon-trash"></i>Borrar</a>
            </td>
        </tr>
    }

</table>